# =============================================================
# PYTHON DUNDER (MAGIC) METHODS
# =============================================================

# Dunder = double underscore (__method__)
# Python calls these automatically in response to built-in operations.
# They let your objects integrate with Python's syntax and built-ins.

# =============================================================
# OBJECT LIFECYCLE
# =============================================================

class MyClass:
    def __new__(cls, *args, **kwargs):
        """Called BEFORE __init__. Creates and returns the instance."""
        print(f"  __new__ called for {cls.__name__}")
        instance = super().__new__(cls)
        return instance

    def __init__(self, value: int):
        """Called AFTER __new__. Initialises the instance."""
        print(f"  __init__ called with value={value}")
        self.value = value

    def __del__(self):
        """Called when the object is about to be garbage-collected."""
        print(f"  __del__ called for value={self.value}")


obj = MyClass(42)
del obj

# =============================================================
# STRING REPRESENTATIONS
# =============================================================

class Vector:
    def __init__(self, x: float, y: float):
        self.x = x
        self.y = y

    def __str__(self) -> str:
        """Human-readable. Called by print() and str()."""
        return f"Vector({self.x}, {self.y})"

    def __repr__(self) -> str:
        """Unambiguous. Called in REPL, repr(), and inside containers."""
        return f"Vector({self.x!r}, {self.y!r})"

    def __format__(self, spec: str) -> str:
        """Called by format() and f-strings with format spec."""
        if spec == "polar":
            import math
            r = math.hypot(self.x, self.y)
            theta = math.degrees(math.atan2(self.y, self.x))
            return f"({r:.2f} ∠ {theta:.1f}°)"
        return f"({self.x:{spec}}, {self.y:{spec}})"


v = Vector(3, 4)
print(str(v))       # Vector(3, 4)
print(repr(v))      # Vector(3, 4)
print(f"{v}")       # Vector(3, 4)
print(f"{v:.2f}")   # (3.00, 4.00)
print(format(v, "polar"))   # (5.00 ∠ 53.1°)

# =============================================================
# ARITHMETIC OPERATORS
# =============================================================

class Vector:
    def __init__(self, x: float, y: float):
        self.x = x
        self.y = y

    # Binary operators
    def __add__(self, other: "Vector") -> "Vector":
        return Vector(self.x + other.x, self.y + other.y)

    def __sub__(self, other: "Vector") -> "Vector":
        return Vector(self.x - other.x, self.y - other.y)

    def __mul__(self, scalar: float) -> "Vector":
        return Vector(self.x * scalar, self.y * scalar)

    def __rmul__(self, scalar: float) -> "Vector":
        """Called when scalar is on the LEFT: 3 * v"""
        return self.__mul__(scalar)

    def __truediv__(self, scalar: float) -> "Vector":
        return Vector(self.x / scalar, self.y / scalar)

    def __neg__(self) -> "Vector":
        return Vector(-self.x, -self.y)

    def __abs__(self) -> float:
        import math
        return math.hypot(self.x, self.y)

    # In-place operators
    def __iadd__(self, other: "Vector") -> "Vector":
        self.x += other.x
        self.y += other.y
        return self

    def __repr__(self) -> str:
        return f"Vector({self.x}, {self.y})"


a = Vector(1, 2)
b = Vector(3, 4)

print(a + b)      # Vector(4, 6)
print(b - a)      # Vector(2, 2)
print(a * 3)      # Vector(3, 6)
print(3 * a)      # Vector(3, 6)  – uses __rmul__
print(b / 2)      # Vector(1.5, 2.0)
print(-a)         # Vector(-1, -2)
print(abs(b))     # 5.0

a += Vector(10, 10)
print(a)          # Vector(11, 12)

# =============================================================
# COMPARISON OPERATORS
# =============================================================

from functools import total_ordering

@total_ordering   # auto-generates missing comparisons from __eq__ and __lt__
class Temperature:
    def __init__(self, celsius: float):
        self.celsius = celsius

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Temperature):
            return NotImplemented
        return self.celsius == other.celsius

    def __lt__(self, other: "Temperature") -> bool:
        if not isinstance(other, Temperature):
            return NotImplemented
        return self.celsius < other.celsius

    def __repr__(self) -> str:
        return f"Temperature({self.celsius}°C)"


t1 = Temperature(100)
t2 = Temperature(0)
t3 = Temperature(100)

print(t1 == t3)   # True
print(t1 > t2)    # True   – generated by @total_ordering
print(t2 <= t1)   # True
print(sorted([t1, t2, Temperature(37)]))

# =============================================================
# CONTAINER / SEQUENCE PROTOCOL
# =============================================================

class NumberList:
    def __init__(self, *values):
        self._data = list(values)

    def __len__(self) -> int:
        return len(self._data)

    def __getitem__(self, index):
        return self._data[index]

    def __setitem__(self, index, value):
        self._data[index] = value

    def __delitem__(self, index):
        del self._data[index]

    def __contains__(self, item) -> bool:
        return item in self._data

    def __iter__(self):
        return iter(self._data)

    def __reversed__(self):
        return reversed(self._data)

    def __repr__(self) -> str:
        return f"NumberList({self._data})"


nl = NumberList(10, 20, 30, 40, 50)
print(len(nl))          # 5
print(nl[0])            # 10
print(nl[-1])           # 50
print(nl[1:3])          # [20, 30]
print(30 in nl)         # True
print(list(reversed(nl)))
for x in nl:
    print(x, end=" ")
print()

# =============================================================
# CALLABLE OBJECTS
# =============================================================

class Multiplier:
    def __init__(self, factor: float):
        self.factor = factor

    def __call__(self, value: float) -> float:
        return value * self.factor

    def __repr__(self) -> str:
        return f"Multiplier(x{self.factor})"


double = Multiplier(2)
triple = Multiplier(3)

print(double(5))     # 10
print(triple(5))     # 15
print(callable(double))  # True

# =============================================================
# CONTEXT MANAGER PROTOCOL
# =============================================================

class Timer:
    import time as _time

    def __enter__(self):
        import time
        self._start = time.perf_counter()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        import time
        self.elapsed = time.perf_counter() - self._start
        print(f"Elapsed: {self.elapsed:.6f}s")
        return False   # don't suppress exceptions

with Timer() as t:
    total = sum(range(1_000_000))

print(f"Sum: {total}")

# =============================================================
# HASHING  (__hash__)
# =============================================================

# Objects used as dict keys or set members must be hashable.
# If you define __eq__, Python sets __hash__ = None (unhashable).
# Define __hash__ explicitly to keep hashability.

class Point:
    def __init__(self, x: int, y: int):
        self.x = x
        self.y = y

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Point):
            return NotImplemented
        return (self.x, self.y) == (other.x, other.y)

    def __hash__(self) -> int:
        return hash((self.x, self.y))

    def __repr__(self) -> str:
        return f"Point({self.x}, {self.y})"


p1 = Point(1, 2)
p2 = Point(1, 2)
p3 = Point(3, 4)

print(p1 == p2)     # True
print(hash(p1) == hash(p2))  # True

points = {p1, p2, p3}   # works because __hash__ is defined
print(points)            # {Point(1, 2), Point(3, 4)}

d = {p1: "home", p3: "office"}
print(d[p2])     # "home" – p2 equals p1, same hash

# =============================================================
# ATTRIBUTE ACCESS
# =============================================================

class AttrLogger:
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)

    def __getattr__(self, name: str):
        """Called only when normal attribute lookup fails."""
        print(f"  __getattr__: '{name}' not found, returning default")
        return None

    def __setattr__(self, name: str, value):
        """Called on EVERY attribute assignment."""
        print(f"  __setattr__: {name} = {value!r}")
        super().__setattr__(name, value)

    def __delattr__(self, name: str):
        print(f"  __delattr__: {name}")
        super().__delattr__(name)


obj = AttrLogger(x=1, y=2)
print(obj.x)        # 1
print(obj.z)        # __getattr__ – z not found
obj.z = 99          # __setattr__
del obj.z           # __delattr__

# =============================================================
# DUNDER REFERENCE TABLE
# =============================================================

print("""
Lifecycle:      __new__  __init__  __del__
Strings:        __str__  __repr__  __format__  __bytes__
Arithmetic:     __add__  __sub__  __mul__  __truediv__  __floordiv__  __mod__
                __pow__  __neg__  __pos__  __abs__  __round__
                __radd__ __rsub__ __rmul__ (reflected – right-hand operand)
                __iadd__ __isub__ __imul__ (in-place / augmented assignment)
Comparison:     __eq__  __ne__  __lt__  __le__  __gt__  __ge__
Container:      __len__  __getitem__  __setitem__  __delitem__
                __contains__  __iter__  __reversed__  __next__
Callable:       __call__
Context mgr:    __enter__  __exit__
Attribute:      __getattr__  __getattribute__  __setattr__  __delattr__
Hashing:        __hash__
Boolean:        __bool__
Numeric conv:   __int__  __float__  __complex__  __index__
Bitwise:        __and__  __or__  __xor__  __lshift__  __rshift__  __invert__
""")
